### ISSUE TITLE
Trending Products, Best Sales, New Arrivals and Popular Category section on home page not giving expected results.

### ISSUE THREAD

**Issue by Abk0710** [Anikesh02/ShopMart#8]
I noticed that the Trending Products, Best Sales, New Arrivals, and Popular Category sections on the home page are not being displayed as expected .The products in this section are not updating properly based on the sales data, or the section is empty.The issue may be related to frontend rendering, data fetching from the backend, or incorrect use of layout components.
I would like to investigate and work on resolving this issue to improve the user experience on the home page. Please assign this issue to me so that I can work on diagnosing the root cause and implementing a solution. I will provide regular updates on my progress and seek feedback if needed.

**Comment by Anikesh02** [comment]
Go for it
